package by.htp.jd2.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, 
	GO_TO_REGISTRATION_PAGE, 
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS, 
	DO_LOG_IN, DO_LOG_OUT, 
	DO_REGISTRATION,
	
	ADD_NEWS,	
	EDIT_NEWS,
	DELETE_NEWS,
	GO_TO_DO_ACTION,
	DO_ACTION_PROVIDER,
	CHECKED_NEWS,
	CHANGE_LANGUAGE,
}
